### PR TITLE
Rebuild for r-base-3.6.1

### PR DESCRIPTION
**Pull request by xhochy**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
FYI, the migration bot should get around to all of the recipes within the next few days.

**Comment by xhochy** [comment]
@dpryan79 I'm aware of this but I'm fast-tracking this to unblock https://github.com/conda-forge/staged-recipes/pull/8862

**Comment by dpryan79** [comment]
Ah, gotcha

**Comment by xhochy** [comment]
Thanks @dpryan79 for the fast merge!

**Pull request merged**
